name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Run dependency check (non-fatal)
        run: npm run check-deps || true

      - name: Run quick tests (if present)
        run: npm test --if-present

      - name: Build
        run: npm run build --if-present

      - name: Lint (if available)
        run: npm run lint --if-present

      # Optional: run Lighthouse against a deployed URL if you provide LIGHTHOUSE_URL
      # - name: Lighthouse audit
      #   uses: treosh/lighthouse-ci-action@v2
      #   with:
      #     url: ${{ secrets.LIGHTHOUSE_URL }}
